### ISSUE TITLE
Controls do not hide when video is played fullscreen

### ISSUE THREAD

**Issue by ZippyWonderdust** [Equiel-1703/udemy-video-fix#1]
First; thank you so much for coding this script! It both amazes and frustrates me that Udemy, a site that teaches coding, cannot fix their own software. This display bug has been driving me insane and I am so grateful that you have coded a workaround for it.

It appears to not be working in fullscreen mode; the controls never hide.  I am using Firefox 132.0.2 on Gnome on Linux and running your script in Tampermonkey 5.3.2.  Let me know if you need any more details.

**Comment by Equiel-1703** [comment]
Hey friend! I'm so happy you found my script useful! Thank you so much for the feedback!

I tried to reproduce the bug you reported in Chrome and I couldn't. But when I tried in Firefox, the exact bug you described occurred.

Based on my testing, this seems to be a Firefox-only issue. I think Firefox resizes divs in a different way than Chrome does, and this is confusing the script - but this is just my speculation.

I'm working on a solution for this, and I'll let you know of any updates!

**Comment by Equiel-1703** [comment]
Hey friend! I fixed the problem you related on the new version of the script (v1.2).

Please, let me know if this worked for you!

Cheers,
Henrique.

**Comment by ZippyWonderdust** [comment]
Darn it! I missed your reply earlier. I’ll try it out tomorrow and let you know how it works.

**Comment by ZippyWonderdust** [comment]
Yup; it appears to work just fine now.  Excellent! Thank you so much!

**Comment by Equiel-1703** [comment]
You're very welcome! Thank you for the feedback!
